config/routes.rb
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
# Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
# Can be used by load balancers and uptime monitors to verify that the app is live.
# Defines the root path route ("/")
# root "posts#index"

    # get "/articles" ,to: "articles#index"


    # get "/articles", to: "articles#index"


    # get "/articles/:id", to: "articles#show"


 Rails.application.routes.draw do
    root "articles#index"
    resources :articles do
        resources :comments
    end
    resources :authors
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
  belongs_to :author

  def author_full_name
    "#{author.firstname} #{author.lastname}"
  end

end

app/models/author.rb
class Author < ApplicationRecord
  has_many :articles

  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :email, presence: true , uniqueness: true

end

app/models/comment.rb
class Comment < ApplicationRecord
include Visible
  belongs_to :article

end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = ['public', 'private', 'archived']

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    def public_count
      where(status: 'public').count
    end
  end

  def archived?
    status == 'archived'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]

  def index
    @articles = Article.all
  end
  def show
    @article = Article.find(params[:id])
  end

  def new
     @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to @article
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
      @article = Article.find(params[:id])
      @article.destroy

      redirect_to root_path, status: :see_other
  end


  private
    def article_params
      params.require(:article).permit(:title, :body, :status, :author_id)
    end

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end
  def show
    @author = Author.find(params[:id])
  end

  def new

     @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    @author.save
    redirect_to @author
  end
  def edit
    @author = Author.find(params[:id])
  end

  def update
    @author = Author.find(params[:id])

    if @author.update(author_params)
      redirect_to @author
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
      @author = Author.find(params[:id])
      @author.destroy

      redirect_to authors_path, status: :see_other
  end


  private
    def author_params
      params.require(:author).permit(:firstname, :lastname, :email)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article), status: :see_other
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body, :status)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_article.html.erb
<li>
<%= article.title %> <%= link_to "Read here.", article %>
</li>

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>

  <div style="padding:10px">

    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
     <%= message %>
    <% end %><br>
  
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
    <%= message %>
    <% end %>
    <%= form.label :status %><br>
    <%= form.select :status, Visible::VALID_STATUSES, selected: article.status || 'public' %><br>

    <%= form.label :author_id %><br>
    <%= form.select :author_id, Author.all.map { |author| [author.firstname, author.id] }, { prompt: 'Select Author' } %><br><br>
    <%= form.submit  %>
  
  </div>
<% end %>

app/views/articles/edit.html.erb
<h2>Edit Article</h2>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1>Articles</h1>

<h4 style="padding:20px">Our blog has <%= Article.public_count %> articles </h4>

<ul>
  <% @articles.each do |article| %>
    <% unless article.archived? %>
      <li>
        <%= link_to article.title , article %> <i style="color:gray;font-size:11px"> <%= article.author_full_name %> </i>
      </li>
    <% end %>
  <% end %>
</ul>

<%= link_to "New Article", new_article_path %>
<br>
<%= link_to "List of Author",authors_path %>
<br>

app/views/articles/new.html.erb
<h1>New Article</h1><br>
<%= render "form", article: @article %>

app/views/articles/show.html.erb
<h1 style="padding:20px" >Title: <%= @article.title %></h1>  

<p>body:<br> <%= @article.body %></p>

<% if @article.status == 'public' %>
  <i class="bi bi-0-circle-fill" style="color:green"></i>
  <% else %>
  <i class="bi bi-0-circle-fill" style="color:red"></i>
<% end %>
<br>

<p><i class="bi bi-pen-fill"></i> <%= @article.author_full_name %> </p>

<%= link_to "Back", "/" %>
  <%= link_to "Edit", edit_article_path(@article) %>
  <%= link_to "Delete", article_path(@article), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>
<br><br>
<h4>Comments</h4>
<%= render @article.comments %>
<br>
<h5>Add a comment:</h5>
<%= render 'comments/form' %>

app/views/authors/_form.html.erb
<%= form_with model: author do |form| %>
  <div>
    <%= form.label :firstname %><br>
    <%= form.text_field :firstname %>
    <% author.errors.full_messages_for(:firstname).each do |message| %>
     <%= message %><br>
    <% end %>
  
    <br><%= form.label :lastname %><br>
    <%= form.text_field :lastname %>
    <% author.errors.full_messages_for(:lastname).each do |message| %>
      <%= message %>
    <% end %>
  
    <br><%= form.label :email %><br>
    <%= form.text_field :email %><br>
    <% author.errors.full_messages_for(:email).each do |message| %>
      <%= message %>
    <% end %>
  <br><br>
    <%= form.submit %>
  
  <div>

</div>
<% end %>

app/views/authors/edit.html.erb
<h2>Edit Author</h2>

<%= render "form", author: @author %>

app/views/authors/index.html.erb
<h1>List Of Authors</h1>

<%= link_to "Create Author", new_author_path, class: "btn btn-primary"  %>


<table class="table table-striped">
  <% @authors.each do |author| %>
  <tr>

      <td>
        <%=  author.firstname  %>
      </td>
      <td>
        <%=  author.lastname  %>
      </td>
      <td>
        <%=author.email %>
      </td>
      <td>
      <%= link_to "Details", author%> 
      </td>
      </tr>
    <% end %>
  
</table>

<p></p>

app/views/authors/new.html.erb
<h1>New Author</h1>
<%= render "form", author: @author %>

app/views/authors/show.html.erb
<h2>Author Details</h2>
<div style="padding:20px ; background-color:beige">
<p>Name: <b><%= @author.firstname %></b></p>
<p>LastName:<b><%= @author.lastname %></b></p>
<p>Email:<b> <%= @author.email %></b></p>

<div style="border-top:1px solid black;padding:5px">
<%= link_to "Back", authors_path %>
  <%= link_to "Edit", edit_author_path(@author) %>
  <%= link_to "Delete", author_path(@author), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>

</div>
</div>

<h4>Author Posts:</h4>
<ul>
<%= render @author.articles %>
</ul>

app/views/comments/_comment.html.erb
<% unless comment.archived? %>
<div style="border:1px dotted gray ; margin:6px ">
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
  <p>
    <%= link_to "Delete Comment", [comment.article, comment], data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                } %>
  </p>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <div style="border:1px solid gray;background-color:#44444444 ; margin:10px ; padding:15px">
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
 
  <p>This comment should be:
  <%= form.label :status %>
  <%= form.select :status, Visible::VALID_STATUSES, selected: 'public' %>
</p>
 <p>
    <%= form.submit %>
  </p>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <style>
     body{
      background-color:#55221155;
     }
    </style>
  </head>

  <body>
   
    <div class="row">
    <div class="col-sm-2">
    </div>
    <div class="col-sm-8">
        <%= yield %>
    </div>
    <div class="col-sm-2">
    </div>
    </div>
   
  </body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</html>